dist: trusty
sudo: required
language: csharp
mono: none
env: DOTNETCORE=1
solution: ./DB-Location-XReferencer/DB-Location-XReferencer.sln

script:
 - cd DB-Location-XReferencer
 - dotnet restore
 - dotnet build