language: csharp
solution: DB-Location-XReferencer.sln
mono: none
dotnet: 1.1.5
install:
  - nuget restore DB-Location-XReferencer.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - dotnet restore