dist: trusty
sudo: required
language: csharp
mono: none
dotnet: 2.0.0
solution: ./DB-Location-XReferencer/DB-Location-XReferencer.sln

script:
 - cd DB-Location-XReferencer
 - dotnet restore
 - dotnet build