dist: trusty
sudo: required
language: csharp
solution: DB-Location-XReferencer.sln

#script:
# - cd DB-Location-XReferencer
# - dotnet restore
# - dotnet build -f net452
 
install:
  - cd DB-Location-XReferencer
  - nuget restore DB-Location-XReferencer.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
# Note: Can remove all below if not running unit tests
  - msbuild /p:Configuration=Release DB-Location-XReferencer.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DB-Location-XReferences.Tests/bin/Debug/DB_Location_XReferences.Tests.dll
 
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore1x