# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
# See: https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
#version: 1.0.{build}


image: Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
#onfiguration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  #parallel: true                  # enable MSBuild parallel builds
  project: ./DB-Location-XReferencer/DB-Location-XReferencer.sln      # path to Visual Studio solution or project
  
  # MSBuild verbosity level
  #verbosity: quiet|minimal|normal|detailed